### ISSUE TITLE
morgue not working when using tmux

### ISSUE THREAD

**Issue by abelmathew** [backtrace-labs/backtrace-morgue#1]
```
[amathew@backtracehq] ~/minidump_handmadecon/windows/reduced
08:34:40pm 10040 $ morgue login https://yolo.sp.backtrace.io
User: admin
Password: ************

Unable to authenticate: socket hang up

``` 

This only happens when I'm running under tmux. Everything works as expected when not running under tmux.

**Comment by abelmathew** [comment]
[morgue_strace.txt](https://github.com/backtrace-labs/backtrace-morgue/files/659192/morgue_strace.txt)

**Comment by wca** [comment]
FWIW, I've used morgue under tmux for a while and never seen this issue, so other variables seem likely to be involved.
