### ISSUE TITLE
Login with SSO credentials

### ISSUE THREAD

**Issue by abyrd-phx** [backtrace-labs/backtrace-morgue#109]
I'm attempting to use morgue and getting
> Error: Unable to authenticate: HTTP 401: Unauthorized.

My company hosts backtrace on site and when using the web interface we log in with our company single sign on credentials. How can I use `morgue` in this environment?

**Comment by rick-bt** [comment]
Hi abyrd-phx - try [this doc](https://support.backtrace.io/hc/en-us/articles/360040515871-How-can-I-login-to-the-morgue-tool-via-SSO) to use a token with morgue.

**Comment by abyrd-phx** [comment]
I no longer get prompted for a username and password, but I still receive "HTTP 401: Unauthorized"

**Comment by abyrd-phx** [comment]
Got it working. Had to use an internal subdomain with less protection. Thanks a bunch for the pointer. Tossing a link to that in the readme could be beneficial.
