### ISSUE TITLE
Use of AbortController requires nodejs >= v15.4.0

### ISSUE THREAD

**Issue by cstrahan** [backtrace-labs/backtrace-morgue#119]
`AbortController` was added as an experimental feature in nodejs versions `v15.0.0` and `v14.17.0`, and made stable in `v15.4.0` (see https://nodejs.org/dist/latest/docs/api/globals.html#globals_class_abortcontroller).

But we made use of `AbortController` in https://github.com/backtrace-labs/backtrace-morgue/pull/114, without bumping the minimum required version. Consequently, smoke tests are failing due to nodejs v14 being used.

@konraddysput could we either make the `AbortController` dependency optional (through runtime support detection), or bump the minimum nodejs version in the `package.json`?

**Comment by konraddysput** [comment]
We have our own version of the abort controller - minimal that does the work and we trust it even more than making conditional checks for runtime.

**Comment by konraddysput** [comment]
should be closed by #120.
