### ISSUE TITLE
On ubuntu server 16.04 get npm warn

### ISSUE THREAD

**Issue by RioAraki** [backtrace-labs/backtrace-morgue#25]
Try to install on ubuntu server 16.04 with `sudo npm install -g backtrace-morgue` but get `npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself`. But by checking the package folder I do see `ajv` and `ajvkeywords` being installed. Not sure if this warning msg matters?

**Comment by sbahra** [comment]
Hi Rio,

Thanks for this. This is a known issue and benign.
