### ISSUE TITLE
how to filter by issue state?

### ISSUE THREAD

**Issue by rugbbyli** [backtrace-labs/backtrace-morgue#85]
Hi, I want to list issues with state open, which I could done on web ui like this:
<img width="360" alt="image" src="https://user-images.githubusercontent.com/6150013/161371587-e6dfdead-afe5-40dd-ba0c-7d709b3a40ac.png">
When I tried using `morgue list project --filter=state,equal,open`, it show `Error: Filter column not found`. 

So how to do this using morgue, or is it even possible?

**Comment by wbormans-backtrace** [comment]
If you go to Backtrace and filter, you can actually see the filters appear in the URI. For example, in this case you'd see a URL that looks like this: `https://universe.sp.backtrace.io/p/project/triage?filters=(fingerprint%3Bissues%3Bstate%3Dopen)`. Using some URL decoding on that, we can see the filters are set to `(fingerprint;issues;state=open)`.

If you use `--filter="fingerprint;issues;state,equal,open"`, you should be able to filter.

**Comment by rugbbyli** [comment]
Wow it works as you said, thanks.

**Comment by konraddysput** [comment]
Followup information: 

You should be able to also use this parameter `--filter='fingerprint;issues;state',equal,open`
